# Generated by Django 5.2.3 on 2025-07-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatlog',
            name='description',
        ),
        migrations.AddField(
            model_name='blockedip',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='threatlog',
            name='protcol',
            field=models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='tcp', max_length=10),
        ),
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], max_length=10)),
                ('port', models.IntegerField()),
                ('action', models.CharField(choices=[('ACCEPT', 'ACCEPT'), ('DROP', 'DROP')], max_length=10)),
                ('direction', models.CharField(choices=[('INPUT', 'INPUT'), ('OUTPUT', 'OUTPUT')], max_length=10)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Firewall Rule',
                'verbose_name_plural': 'Firewall Rules',
                'constraints': [models.UniqueConstraint(fields=('protocol', 'port', 'action', 'direction'), name='unique_firewall_rule')],
            },
        ),
    ]
