# Generated by Django 5.2.3 on 2025-07-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_threatlog_description_blockedip_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallrule',
            name='dest_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='dest_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='name',
            field=models.CharField(default='Unnamed Rule', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='source_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firewallrule',
            name='description',
            field=models.TextField(blank=True, default='No description added', max_length=255, null=True),
        ),
    ]
